### PR TITLE
Remove marked a direct dev dependency

### PR DESCRIPTION
**Pull request by roback**
It was added in 209104f.

It causes the vulnerability in #34 to be shown twice and it doesn't seem to be needed anymore.

From https://github.com/twingly/twingly-search-api-node/issues/34#issuecomment-484434627

### CODE REVIEW

**Comment by walro** [comment]
how did you remove it? surprised to see that the lock file was untouched

did you just yank the row or did you do `npm uninstall`?

**Comment by roback** [comment]
I just removed the line manually, but the result is the same if you run `npm uninstall marked`. The lock file stays unchanged, hence the *"it doesn't seem to be needed anymore"* in the description :)

**Comment by walro** [comment]
I don't think it was ever needed, really :)

**Comment by walro** [comment]
we could probably just have re-installed  `jsdoc`to get the latest allowed marked, rather than adding the direct dependency. That's why the lock files does not change here.

**Comment by roback** [comment]
> we could probably just have re-installed `jsdoc`to get the latest allowed marked, rather than adding the direct dependency. That's why the lock files does not change here.

🤦‍♂️

**Pull request merged**
