### PR TITLE
Update client to Search API v3

### PR DESCRIPTION
**Pull request by roback**
The same changes as in the ruby client (twingly/twingly-search-api-ruby#65)

I noticed a few things that could be improved, but I think it's easier to handle those in a separate PR. 
For example:

* a few variables are still using snake_case
* some tests changing the environment for other tests
* recording fixtures requires you to remove your API key by editing the fixture by hand

### CODE REVIEW

**Comment by dentarg** [comment]
I can add test for longitude/latitude of `coordinates`

**Comment by dentarg** [comment]
Hmm, I think this should be fixed too, I can take a look.

```
$ dotenv node examples/hello_world.js
fullSearchQuery="hello world" start-date:2017-05-29 12:13:30
...
```

**Comment by dentarg** [comment]
@roback I was going to request review by you but it's not possible :)

**Comment by roback** [comment]
> @roback I was going to request review by you but it's not possible :)

Hehe, I can take a look anyway :)

**Pull request merged**
